# Generated by Django 2.2 on 2020-08-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tipoMaterial', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPersona', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('numLibros', models.IntegerField()),
                ('adeudo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSalida', models.CharField(max_length=50)),
                ('fechaRegreso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='biblioteca.Persona')),
                ('matricula', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('biblioteca.persona',),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.Material')),
                ('editorial', models.CharField(max_length=50)),
            ],
            bases=('biblioteca.material',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='biblioteca.Persona')),
                ('numEmpleado', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('biblioteca.persona',),
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.Material')),
            ],
            bases=('biblioteca.material',),
        ),
        migrations.AddField(
            model_name='persona',
            name='prestamo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Prestamo'),
        ),
        migrations.AddField(
            model_name='material',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Prestamo'),
        ),
    ]
